version: "2"
checks:
  file-lines:
    enabled: false
  method-lines:
    enabled: false
plugins:
  credo:
    enabled: false
  duplication:
    enabled: true
    checks:
      Similar code:
        enabled: false
    config:
      languages:
        javascript:
          mass_threshold: 75
