defmodule Ameritrade.Balances do
  defstruct accruedInterest: 0,
            availableFundsNonMarginableTrade: 0,
            bondValue: 0,
            buyingPower: 0,
            cashBalance: 0,
            cashAvailableForTrading: 0,
            cashReceipts: 0,
            dayTradingBuyingPower: 0,
            dayTradingBuyingPowerCall: 0,
            dayTradingEquityCall: 0,
            equity: 0,
            equityPercentage: 0,
            liquidationValue: 0,
            longMarginValue: 0,
            longOptionMarketValue: 0,
            longStockValue: 0,
            maintenanceCall: 0,
            maintenanceRequirement: 0,
            margin: 0,
            marginEquity: 0,
            moneyMarketFund: 0,
            mutualFundValue: 0,
            regTCall: 0,
            shortMarginValue: 0,
            shortOptionMarketValue: 0,
            shortStockValue: 0,
            totalCash: 0,
            isInCall: false,
            unsettledCash: 0,
            pendingDeposits: 0,
            marginBalance: 0,
            shortBalance: 0,
            accountValue: 0
end
