defmodule Ameritrade.Order do
@moduledoc false
  defstruct session: nil,
            duration: nil,
            orderType: nil,
            cancelTime: nil,
            complexOrderStrategyType: nil,
            quantity: 0,
            filledQuantity: 0,
            remainingQuantity: 0,
            requestedDestination: nil,
            destinationLinkName: nil,
            releaseTime: nil,
            stopPrice: 0,
            stopPriceLinkBasis: nil,
            stopPriceLinkType: nil,
            stopPriceOffset: 0,
            stopType: nil,
            PriceLinkBasis: nil,
            PriceLinkType: nil,
            price: nil,
            taxLotMethod: nil,
            orderLegCollection: [],
            activationPrice: 0,
            specialInstruction: nil,
            orderStrategyType: nil,
            orderId: nil,
            cancelable: false,
            editable: false,
            status: nil,
            enteredTime: nil,
            closeTime: nil,
            accountId: 0,
            orderActivityCollection: [],
            replacingOrderCollection: [],
            childOrderStrategies: [],
            statusDescription: nil
end

defmodule Ameritrade.Order.Saved do
@moduledoc false
  defstruct session: nil,
            duration: nil,
            orderType: nil,
            cancelTime: nil,
            complexOrderStrategyType: nil,
            quantity: 0,
            filledQuantity: 0,
            remainingQuantity: 0,
            requestedDestination: nil,
            destinationLinkName: nil,
            releaseTime: nil,
            stopPrice: 0,
            stopPriceLinkBasis: nil,
            stopPriceLinkType: nil,
            stopPriceOffset: 0,
            stopType: nil,
            priceLinkBasis: nil,
            priceLinkType: nil,
            price: 0,
            taxLotMethod: nil,
            orderLegCollection: [],
            activationPrice: 0,
            specialInstruction: nil,
            orderStrategyType: nil,
            orderId: 0,
            cancelable: false,
            editable: false,
            status: nil,
            enteredTime: nil,
            closeTime: nil,
            tag: nil,
            accountId: 0,
            orderActivityCollection: [],
            replacingOrderCollection: [],
            childOrderStrategies: [],
            statusDescription: nil,
            savedOrderId: 0,
            savedTime: nil
end

defmodule Ameritrade.Order.Strategies do
@moduledoc false
  defstruct session: nil,
            duration: nil,
            orderType: nil,
            cancelTime: nil,
            complexOrderStrategyType: nil,
            quantity: 0,
            filledQuantity: 0,
            remainingQuantity: 0,
            requestedDestination: nil,
            destinationLinkName: nil,
            releaseTime: nil,
            stopPrice: 0,
            stopPriceLinkBasis: nil,
            stopPriceLinkType: nil,
            stopPriceOffset: 0,
            stopType: nil,
            priceLinkBasis: nil,
            priceLinkType: nil,
            price: 0,
            taxLotMethod: nil,
            orderLegCollection: []
end

defmodule Ameritrade.Order.Leg.Collection do
@moduledoc false
  defstruct orderLegType: nil,
            legId: 0,
            instrument: nil,
            instruction: nil,
            positionEffect: nil,
            quantity: 0,
            quantityType: nil
end
